FROM node:14

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY feup-exchange/ .

# Production version of npm install
RUN npm ci --only=production

EXPOSE 8080
CMD [ "npm", "start" ]
